AWSTemplateFormatVersion: '2010-09-09'
Description: Client Request & Approval System Backend

Parameters:
  Environment:
    Type: String
    Default: production

  LambdaS3Bucket:
    Type: String
    Default: ''

  LambdaS3Key:
    Type: String
    Default: ''

  AllowedOrigins:
    Type: String
    Default: '*'

Conditions:
  UseProvidedArtifacts: !And
    - !Not [!Equals [!Ref LambdaS3Bucket, '']]
    - !Not [!Equals [!Ref LambdaS3Key, '']]

Resources:
  # ------------------------------------------------------------
  # S3 bucket for Lambda artifacts (auto-created)
  # ------------------------------------------------------------
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Condition: !Not [UseProvidedArtifacts]
    Properties:
      BucketName: !Sub '${AWS::StackName}-lambda-artifacts'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ------------------------------------------------------------
  # DynamoDB
  # ------------------------------------------------------------
  ClientRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-ClientRequests'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # ------------------------------------------------------------
  # IAM Role for Lambda
  # ------------------------------------------------------------
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  # ------------------------------------------------------------
  # Example Lambda (pattern for others)
  # ------------------------------------------------------------
  CreateRequestFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CreateRequest'
      Runtime: nodejs18.x
      Handler: CreateRequest.handler
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !If
          - UseProvidedArtifacts
          - !Ref LambdaS3Bucket
          - !Ref LambdaArtifactsBucket
        S3Key: !If
          - UseProvidedArtifacts
          - !Ref LambdaS3Key
          - 'bootstrap.zip'
      Environment:
        Variables:
          TABLE_NAME: !Ref ClientRequestsTable
          ENVIRONMENT: !Ref Environment

Outputs:
  LambdaArtifactsBucketName:
    Description: Bucket used for Lambda artifacts
    Value: !If
      - UseProvidedArtifacts
      - !Ref LambdaS3Bucket
      - !Ref LambdaArtifactsBucket

  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref ClientRequestsTable

  ApiGatewayUrl:
    Description: Placeholder (API Gateway added next)
    Value: !Sub 'https://example.execute-api.${AWS::Region}.amazonaws.com/${Environment}'